core/urls.py
from django.urls import path
from .views import *

app_name = 'core'

urlpatterns = [
    path('', shorten_url, name='home'),
]

urlshortner/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    re_path(r'^static/(.*)$', serve, {'document.root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models

# Create your models here.
class URL(models.Model):
    original_url = models.URLField()
    short_url = models.CharField(max_length=10, null=True, blank=True)

    def __str__(self) -> str:
        return f"the original url is {self.original_url} and the short url is {self.short_url}"

core/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import URL
from hashids import Hashids
from .shortener import short

hashids = Hashids(min_length=4, salt='mangos')

# Create your views here.
def shorten_url(request):
    if request.method == 'POST':
        original_url = request.POST['url']
        short_url = short(original_url)

        url = URL(original_url=original_url, short_url=short_url)

        url.save()

        # url, created = URL.objects.get_or_create(original_url=original_url)
        
        # if created:
        #     url.save()

        # short_url = shorten_url(url)
        # short_url.save()
        return render(request, 'home.html', {'short_url': short_url})
    return render(request, 'home.html')

        

core/templates/home.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title>URL Shortener</title>
    <meta name="viewport" content="width=device-width, intial-scale=1.0">
    <link href="{% static 'style.css' %}" rel="stylesheet"> 
    <script src="{% static 'script.js' %}" defer></script>
</head>
<body>
    <h1>Shorten URLs</h1>
    <div class="card">
        <form class="form-control" method="POST" action="{% url 'core:home'%}">
            {% csrf_token %}
            <input type="url" name="url" placeholder="Enter URL" required>
            <button type="submit">Shorten</button>
        </form>
        <div class="output">
        {% if short_url %}
            <p>Short URL: <a href="{{ short_url }}" id="short-url"><span>{{ short_url }}</span></a></p>
            <button id="copy-url">copy</button>
        </div>
        {% endif %}
    </div>
</body>
</html>